### PR TITLE
Major README refactor with aws/azure sections created in separate docs

### LINKED ISSUE #9: README improvements - initial pass
Attempt to clarify the README for this project and provide a better context flow.  This repository is maintained by the IBM Spectrum Scale development team, so naturally it's under the IBM org, The  "ibm-spectrum-scale" in "ibm-spectrum-scale-cloud-install" is to further help tie together various github repos that are created by the spectrum scale team. 

This repo does not actually do the work in installing IBM Spectrum Scale, but rather helps to deploy cloud infrastructure resources to AWS and Azure (with more to come in the future)

Opening this issue to help address some feedback that we have gotten from internal users of the repo, which will improve the user experience for anyone who lands here.

- [ ] Clarify the description of the project 
- [ ] Provide a more end to end flow so that the user can visualize what happens after running terraform <-- this needs some more thought. 
- [x] Clarify what are pre-requisites are vs. what the tool will actually do. 
- [x] Validate that there's a minimum clear and base success path  (Follow up with #20)

### PR DESCRIPTION
**Pull request by whowutwut**
This PR builds upon the changes contained in #11.   If we choose to go this path, we should close #11 and merge this one. Resolves #9

This does a **major** refactor of the README file: 
* cloud specific documentation is moved into `docs/` directory
* generated doc files are moved into `docs/gen` directory 
* main README is simplified significantly so users coming to the page can "choose their own adventure" based on the public cloud they are looking for.

### CODE REVIEW

**Comment by whowutwut** [comment]
Some changes went into dev, that caused merge conflicts.  I just rebased this branch to latest with dev and force pushed up.

**Comment by whowutwut** [comment]
Completed the planned changes for now.   This is ready for review.  I prefer this one over #11.

**Comment by whowutwut** [comment]
Friendly reminder @mamuthiah or @sasikeda , could you please review these changes.  If you agree this PR is the path to take opposed to #11.

**Comment by sasikeda** [comment]
@whowutwut Sorry for the delay, I vote for this PR. As a headsup, there are lot more things that are going to be added to README (such as Bastion jump configuration: which allows on-premise users to deploy end-to-end scale, s3backend configuration)

**Pull request merged**
